name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"


      - name: Push to public repo
        run: |
          git clone git@github.com:abhinavpbabu/restaurant-site-demo.git out
          rm -rf out/*
          cp -r dist/* out/
          cd out
          git add .
          git commit -m "Auto deploy"
          git push origin gh-pages
